#' A Reference Class to represent a stepped-wedge cluster-randomised trial.
#'
#' @field clusters List of all clusters stored as a factor.
#' @field study.dt data.table that includes all site and cluster parameters
#'   (some duplicated data).
#' @field cluster.dt data.table that includes cluster parameters \.
#' @field site.dt data.table that includes site parameters.
#' @field data.dt data.table that includes the data from participants.
#'
#' @section Normal simulation
#' @field sim.ppt.per.unit.time.mean Mean patients per unit time (will be forced
#'   positive)
#' @field sim.ppt.per.unit.time.sd Variance in patients per unit time.
#' @field sim.normal.preintervention.mean The outcome before applying any
#'   effects.
#' @field sim.normal.intervention.effect.mean The mean effect of the
#'   intervention across all sites.
#' @field sim.normal.intervention.effect.sd The variance of the intervention
#'   effect between sites.
#' @field sim.site.effect.mean The mean of the effect added separately to each
#'   site.
#' @field sim.site.effect.sd The variance of the effect added separately to each
#'   site.
#' @field sim.site.effect.force.sign Force the time effect to a certain sign
#'   (should be in c(-1,0,+1))
#' @field sim.time.effect.per.unit.mean The mean of the effect added per unit
#'   time for each site.
#' @field sim.time.effect.per.unit.sd The variance of the effect added per unit
#'   time for each site.
#' @field sim.individual.noise.mean The mean of the variance between individuals
#'   for each site.
#' @field sim.individual.noise.sd The variance of the variance between
#'   individuals for each site.
#'
#' @section Permutation testing
#' @field perm.dt A table that holds a number of ways in which to permute sites
#'   to different clusters.
#' @field stat.dt A statistic distribution generated by permuting sites to
#'   different clusters.
#'
#'
#' @export
SW.Study = setRefClass(
  "SW.Study",
  fields = list(clusters = "list",
                study.dt = "data.table",
                cluster.dt = "data.table",
                site.dt = "data.table",
                data.dt = "data.table",

                sim.ppt.per.unit.time.mean = "numeric",
                sim.ppt.per.unit.time.sd = "numeric",
                sim.normal.preintervention.mean = "numeric",
                sim.normal.intervention.effect.mean = "numeric",
                sim.normal.intervention.effect.sd = "numeric",
                sim.site.effect.mean = "numeric",
                sim.site.effect.sd = "numeric",
                sim.site.effect.force.sign = "numeric",
                sim.time.effect.per.unit.mean = "numeric",
                sim.time.effect.per.unit.sd = "numeric",
                sim.individual.noise.mean = "numeric",
                sim.individual.noise.sd = "numeric",

                perm.dt = "data.table",
                stat.dt = "data.table"
                ),
  methods = list(
    initialize = function(clusters = NULL) {
      if (!is.null(clusters)) {
        set.clusters(clusters)
        generate.study.dt()
        generate.cluster.dt()
        generate.site.dt()
      }
    },
    set.clusters = function(clusters) {
      "Replace clusters in the cluster, clusters should be provided as a SW.Cluster object."
      clusterList = clusters
      if (!is.list(clusterList)) clusterList = as.list(clusterList)
      clusters <<- clusterList
    },
    add.clusters = function(clusters.to.add) {
      "Add clusters to the experiment."
      set.clusters(c(clusters, clusters.to.add))
    },
    get.clusters = function() {
      "Get clusters in the study."
      return(clusters)
    },
    get.cluster.names = function() {
      "Get all cluster names."
      unlist(lapply(X = get.clusters(), function(x) x$get.name()))
    },
    get.cluster.by.name = function(cluster.name) {
      "Get a cluster given it's name."
      return(clusters[get.cluster.names() == cluster.name][[1]])
    },
    get.site.by.name = function(site.name) {
      "Get a site given it's name, needs to do a bit of trawling."
      get.site.dt()
      cluster.name = site.dt[site == site.name, cluster]
      return(get.cluster.by.name(cluster.name)$get.site.by.name(site.name))
    },

    get.study.dt = function(force.generate = F) {
      "Get a data.table of the study."
      if (is.null(study.dt) | force.generate) {
        generate.study.dt()
      }
      return(study.dt)
    },
    generate.study.dt = function() {
      "Generate a data.table of the study."
      #For the clusters
      study.dt <<- data.table:::merge.data.table(get.cluster.dt(), get.site.dt())
    },

    get.sites = function(cluster.name = "") {
      "Gets a list of site objects, returning all sites for all cluster if no cluster.name provided."
      if (cluster.name == "") {
        result = list()
        clus = get.clusters()
        for (cluster.ind in 1:length(clus)) {
          result = c(result, clus[[cluster.ind]]$get.sites())
        }
        return(result)
      } else {
        return(get.cluster.by.name(cluster.name)$get.sites())
      }
    },

    get.cluster.dt = function(force.generate = F) {
      "Get a data.table of the clusters in the study."
      if (is.null(cluster.dt) | force.generate) {
        generate.cluster.dt()
      }
      return(cluster.dt)
    },
    generate.cluster.dt = function() {
      "Generate a data.table of the clusters in the study."
      #For the clusters
      cluster.dt <<- data.table::data.table(
        cluster = as.factor(get.cluster.names()),
        cluster.start.time = unlist(lapply(clusters, function(x) x$cluster.start.time)),
        transition.start.time = unlist(lapply(clusters, function(x) x$transition.start.time)),
        intervention.start.time = unlist(lapply(clusters, function(x) x$intervention.start.time)),
        cluster.end.time = unlist(lapply(clusters, function(x) x$cluster.end.time))
      )
      data.table::set(x = cluster.dt, j = 'cluster', value = factor(cluster.dt$cluster))

      #Check there are unique cluster names
      if (length(unique(cluster.dt$cluster)) < nrow(cluster.dt)) {
        warning('Duplicated cluster names are present.')
      }
    },

    get.site.dt = function(force.generate = F) {
      "Get a data.table of the sites in the study."
      if (is.null(site.dt) | force.generate) {
        generate.site.dt()
      }
      return(site.dt)
    },
    generate.site.dt = function() {
      "Generate a data.table of the sites in the study."
      #For the sites
      site.dt <<- data.table::rbindlist(lapply(clusters, function(x) x$generate.site.dt()))
      data.table::set(x = site.dt, j = 'cluster', value = factor(site.dt$cluster))
      data.table::set(x = site.dt, j = 'site', value = factor(site.dt$site))

      #Check there are unique cluster names
      if (length(unique(site.dt$site)) < nrow(site.dt)) {
        warning('Duplicated site names are present.')
      }
    },

    set.sim.parameters = function(sim.ppt.per.unit.time.mean = 10,
                                  sim.ppt.per.unit.time.sd = 2,
                                  sim.normal.preintervention.mean = 15,
                                  sim.normal.intervention.effect.mean = 2,
                                  sim.normal.intervention.effect.sd = .6,
                                  sim.site.effect.mean = 0,
                                  sim.site.effect.sd = 2,
                                  sim.time.effect.per.unit.mean = 0,
                                  sim.time.effect.per.unit.sd = 0.005,
                                  sim.site.effect.force.sign = c(-1,0,+1)[3],
                                  sim.individual.noise.mean = 2,
                                  sim.individual.noise.sd = .4) {
      "Set simulation parameters for the study."
      sim.ppt.per.unit.time.mean <<- sim.ppt.per.unit.time.mean
      sim.ppt.per.unit.time.sd <<- sim.ppt.per.unit.time.sd
      sim.normal.preintervention.mean <<- sim.normal.preintervention.mean
      sim.normal.intervention.effect.mean <<- sim.normal.intervention.effect.mean
      sim.normal.intervention.effect.sd <<- sim.normal.intervention.effect.sd
      sim.site.effect.mean <<- sim.site.effect.mean
      sim.site.effect.sd <<- sim.site.effect.sd
      sim.time.effect.per.unit.mean <<- sim.time.effect.per.unit.mean
      sim.time.effect.per.unit.sd <<- sim.time.effect.per.unit.sd
      sim.site.effect.force.sign <<- sim.site.effect.force.sign
      sim.individual.noise.mean <<- sim.individual.noise.mean
      sim.individual.noise.sd <<- sim.individual.noise.sd

    },

    generate.site.sim.parameters = function() {
      "Generate simultation parameters for each site."
      if (length(sim.normal.preintervention.mean) == 0) {
        warning('Simulation parameters missing, generated using defaults.')
        set.sim.parameters()
      }
      for (cluster in clusters) {
        for (site in cluster$sites) {
          #How many participants per unit time ?
          site$sim.ppt.per.unit.time = abs(rnorm(1,
                                                 mean = sim.ppt.per.unit.time.mean,
                                                 sd = sim.ppt.per.unit.time.sd))

          #Set the mean before intervention.
          site$sim.normal.preintervention.mean = sim.normal.preintervention.mean

          #Add a random site effect.
          site$sim.normal.preintervention.mean = site$sim.normal.preintervention.mean + rnorm(1,
                                                                                              mean = sim.site.effect.mean,
                                                                                              sd = sim.site.effect.sd)

          #Set the mean post intervention, with a random site interaction with intervention
          site$sim.normal.postintervention.mean = site$sim.normal.preintervention.mean + rnorm(1,
                                                                                              mean = sim.normal.intervention.effect.mean,
                                                                                              sd = sim.normal.intervention.effect.sd)
          #Set the variance at the site.
          site$sim.normal.sd = rnorm(1,
                                     mean = sim.individual.noise.mean,
                                     sd = sim.individual.noise.sd)
          #Set the effect per unit time per site.
          site$sim.normal.effect.per.unit.time = rnorm(1,
                                                       mean = sim.time.effect.per.unit.mean,
                                                       sd = sim.time.effect.per.unit.sd)
          #Force sign of time effect if requested.
          if (sim.site.effect.force.sign != 0) {
            site$sim.normal.effect.per.unit.time = sign(sim.site.effect.force.sign) * abs(site$sim.normal.effect.per.unit.time)
          }
        }
      }
    },

    generate.sim.data.tsd = function() {
      "Generate data.dt from Timed.Sampling.Dist object."
      #Get caseload at each site
      gen.dt =  data.table::data.table(site = lapply(get.sites(), function(x) x$name),
                                       sim.ppt.per.unit.time = lapply(get.sites(), function(x) x$sim.ppt.per.unit.time),
                                       site.obj = get.sites())

      #Sort out the resultant data.table
      gen.dt[, site := factor(as.character(site))]
      gen.dt[, sim.ppt.per.unit.time := as.numeric(sim.ppt.per.unit.time)]

      #Merge site and cluster data on
      gen.dt = merge(site.dt, gen.dt)
      gen.dt = data.table:::merge.data.table(cluster.dt, gen.dt, by = 'cluster')
      #Calculate total time for each cluster
      gen.dt[,total.time := cluster.end.time - cluster.start.time]
      #Calculate how many ppts from each cluster
      gen.dt[,n.ppt := round(total.time * sim.ppt.per.unit.time)]

      #Add the simulated patients from a certain site
      message('Generating data from timed sampling distribution...')
      pb <- txtProgressBar(char = '|', style = 3)
      t = Sys.time()
      add.sim.patients = function(site.ind) {
        times = sample(x = gen.dt[site.ind, cluster.start.time]:gen.dt[site.ind, cluster.end.time],
                       size = gen.dt[site.ind, n.ppt],
                       replace = T)
        site.data.dt = data.table::data.table(time = times,
                                              site = gen.dt[site.ind, site],
                                              outcome = gen.dt[site.ind, site.obj][[1]]$get.timed.sampling.dist()$get.value(time = times)
        )
        setTxtProgressBar(pb, site.ind/nrow(site.dt))
        return(site.data.dt)
      }
      data.dt <<- data.table::rbindlist(lapply(1:nrow(site.dt), add.sim.patients))

      close(pb)
      elapsed = Sys.time()-t
      message(paste("Time elapsed: "),hms::as.hms(elapsed))
      message("")

      update.groups.data.dt()
    },

    #TODO: This should proooobably be an implementation of I.Sampler, would need to
    #figure out how to retain intermediate values for animation.
    generate.sim.data.normal = function(save.intermediates = T) {
      "Generates synthetic data, can save the intermediate values for a nice animation if you want."
      #Generate participant IDs
      total.n = 0
      for (cluster in clusters) {
        cluster.n = 0
        for (site in cluster$sites) {
          #Figure out how many participants for that site
          site.n = abs(round(site$sim.ppt.per.unit.time * (cluster$cluster.end.time - cluster$cluster.start.time)))
          #Give them IDs
          start.ppt.id = total.n + cluster.n + 1
          ppt.ids = (start.ppt.id):(start.ppt.id+site.n - 1)
          #Give them randomly distributed times
          times = sample(x = cluster$cluster.start.time:cluster$cluster.end.time, size = site.n, replace = T)
          times = times[order(times)] #(and order so that earlier pptID have earlier time)

          #Set up variables of this site.
          sim.site.dt = data.table::data.table(
            id = ppt.ids,
            time = times,
            site = site$name,
            cluster = cluster$name
          )

          #Initialise simulation data if not done already.
          if (total.n == 0 & cluster.n == 0) {
            data.dt <<- sim.site.dt
          } else {
            data.dt <<- data.table::rbindlist(list(data.dt, sim.site.dt))
          }
          cluster.n = cluster.n + site.n
        }
        total.n = total.n + cluster.n
      }
      #Set factors
      data.table::set(x = data.dt, j = 'site', value = factor(data.dt$site))
      data.table::set(x = data.dt, j = 'cluster', value = factor(data.dt$cluster))

      update.groups.data.dt()

      #Generate synthetic data
      sim.data.intermediate.dt = data.table::copy(data.dt)
      #Each participant gets the grand mean.
      data.table::set(x = sim.data.intermediate.dt,
                      j = 'intermediate.outcome.01',
                      value = sim.normal.preintervention.mean)
      for (cluster.obj in clusters) {
        for (site.obj in cluster.obj$sites) {
          # print(site)
          # print(site.obj$name)
          # print(cluster.obj$name)
          #Add site effect by assigning each participant the pre intervention mean
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[site == site.obj$name & cluster == cluster.obj$name, which=T],
                          j = 'intermediate.outcome.02',
                          value = site.obj$sim.normal.preintervention.mean)
          #Add intervention effect by assigning post intervention mean to intervention participants (copy unchanged values from last operation)
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[group == 'intervention' & site == site.obj$name & cluster == cluster.obj$name, which=T],
                          j = 'intermediate.outcome.03',
                          value = site.obj$sim.normal.postintervention.mean)
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[is.na(intermediate.outcome.03), which = T],
                          j = 'intermediate.outcome.03',
                          value = sim.data.intermediate.dt[is.na(intermediate.outcome.03),intermediate.outcome.02])

          #Add transition effect by drawing from either pre or post intervention (copy unchanged values from last operation)
          #TODO: Smooth transition.
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[group == 'transition' & site == site.obj$name & cluster == cluster.obj$name, which=T],
                          j = 'intermediate.outcome.04',
                          value = sample(x = c(site.obj$sim.normal.postintervention.mean,site.obj$sim.normal.preintervention.mean),
                                         size = sim.data.intermediate.dt[group == 'transition' & site == site.obj$name & cluster == cluster.obj$name, .N],
                                         replace = T))
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[is.na(intermediate.outcome.04), which = T],
                          j = 'intermediate.outcome.04',
                          value = sim.data.intermediate.dt[is.na(intermediate.outcome.04),intermediate.outcome.03])

          #Add time effect
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[site == site.obj$name & cluster == cluster.obj$name, which=T],
                          j = 'intermediate.outcome.05',
                          value = sim.data.intermediate.dt[site == site.obj$name & cluster == cluster.obj$name,intermediate.outcome.04 + time * site.obj$sim.normal.effect.per.unit.time])
          #Calculate noise noise
          # noise.sd = site.obj$sim.normal.sd
          data.table::set(x = sim.data.intermediate.dt,
                          i = sim.data.intermediate.dt[site == site.obj$name & cluster == cluster.obj$name, which=T],
                          j = 'noise',
                          value = rnorm(n = sim.data.intermediate.dt[site == site.obj$name & cluster == cluster.obj$name, .N],
                                        mean = 0,
                                        sd = site.obj$sim.normal.sd))

        }
      }
      #Add noise.
      data.table::set(x = sim.data.intermediate.dt,
                      j = 'intermediate.outcome.06',
                      value = sim.data.intermediate.dt[,intermediate.outcome.05 + noise])
      #Also assign result to a nicer named column.
      data.table::set(x = sim.data.intermediate.dt,
                      j = 'outcome',
                      value = sim.data.intermediate.dt[,intermediate.outcome.06])

      #Save intermediate values in sim.data if requested.
      if (save.intermediates) {
        data.dt <<- sim.data.intermediate.dt[,list(id,
                                                   cluster,
                                                   time,
                                                   site,
                                                   group,
                                                   outcome,
                                                   intermediate.outcome.01,
                                                   intermediate.outcome.02,
                                                   intermediate.outcome.03,
                                                   intermediate.outcome.04,
                                                   intermediate.outcome.05,
                                                   intermediate.outcome.06)]
      }
    },


    update.groups.data.dt = function() {
      'Updates the group of data.dt according to timing of clusters.'
      # if (!'site' %in% colnames(data.dt)) {
      #   print(colnames(data.dt))
      #   data.dt <<- data.table:::merge.data.table(data.dt, site.dt, by = 'site')
      # }
      data.dt <<- data.table:::merge.data.table(data.dt, site.dt, by = 'site')

      #Get intervention cases and group
      data.dt <<- data.table:::merge.data.table(data.dt, cluster.dt[,.(cluster,transition.start.time,intervention.start.time)], by = 'cluster')

      data.table::set(x = data.dt,
                      j = 'group',
                      value = 'control')
      data.table::set(x = data.dt,
                      i = data.dt[time>=transition.start.time, which = T],
                      j = 'group',
                      value = 'transition')
      data.table::set(x = data.dt,
                      i = data.dt[time>=intervention.start.time, which = T],
                      j = 'group',
                      value = 'intervention')
      data.table::set(x = data.dt,
                      j = 'group',
                      value = factor(data.dt$group))

    },

    #TODO: Best fit lines, maybe colouring facets, highlighting intervention period
    faceted.line.plot = function(dot.size = 2,
                                 ylims = NULL,
                                 outcome.name = 'outcome') {
      "Plots the study as a line plot with facets for different sites. ylims and outcome.name are mainly for animations."
      # xlims = cluster.dt[,c(min(cluster.start.time),max(cluster.end.time))]
      xbreaks = c(cluster.dt$cluster.start.time,
                  cluster.dt$transition.start.time,
                  cluster.dt$intervention.start.time,
                  cluster.dt$cluster.end.time)
      #Basic plot
      p = ggplot2::ggplot(data=data.dt, ggplot2::aes_string(x='time', y=outcome.name, color='cluster')) +
        ggplot2::geom_point(alpha=.3, size = dot.size) +
        ggplot2::theme(legend.position="none",
              panel.grid.minor = ggplot2::element_blank()) +
        ggplot2::labs(x = 'Time', y='Outcome') +
        ggplot2::scale_x_continuous(breaks = xbreaks, minor_breaks = NULL) +
        #The intervention marker
        ggplot2::geom_vline(data=study.dt,
                            ggplot2::aes(xintercept = intervention.start.time),
                            colour = 'red',
                            alpha = .8)

      #Facet by site and cluster if there is more than one site per cluster.
      if (nrow(site.dt) == nrow(cluster.dt)) {
        p = p + ggplot2::facet_grid(cluster ~ .)
      } else {
        p = p + ggplot2::facet_grid(site + cluster ~ .)
      }
      if (!is.null(ylims)) {
        p = p + ggplot2::scale_y_continuous(limits = ylims, minor_breaks = NULL)
      }

      #Highlight intervention period, doesn't work :'(
      # p = p +
      #   geom_rect(data=study.dt,
      #             aes(xmin=transition.start.time,
      #                 xmax=intervention.start.time,
      #                 ymin=-Inf,
      #                 ymax=Inf),
      #             color="blue",
      #             alpha=0.2)

      #Best fit line.
      # geom_line(aes(y=runquantile(data.dt[,get(outcome.name)], k = 40, probs=.5)), colour='black',alpha=0.5)

      return(p)
    },

    cut.data.dt.time.to.periods = function(period.starts) {
      "Cuts the continuous time variable in data.dt into periods, takes a vector of start times for cut"
      data.dt[, period := cut(time, period.starts, include.lowest = T, right = F, ordered_result = T)]
    },

    generate.perm.dt = function(max.r) {
      "Wrapper for function generate.perm.dt in analysis.r"
      perm.dt <<- stepmywedge::generate.perm.dt(study.dt = study.dt, max.r = max.r)
      return(perm.dt)
    },

    generate.stat.dt = function(max.r, outcome.col.name = "outcome", intervention.col.name = "group", stat.per.site = F, statistic = 'WMWU', other.predictors = NULL) {
      "Wrapper for function generate.stat.dt in analysis.r"
      generate.perm.dt(max.r)
      stat.dt <<- stepmywedge::generate.stat.dt(max.r,
                                                outcome.col.name,
                                                intervention.col.name,
                                                data.dt = data.dt,
                                                cluster.dt = cluster.dt,
                                                study.dt = study.dt,
                                                perm.dt = perm.dt,
                                                stat.per.site = stat.per.site,
                                                statistic = statistic,
                                                other.predictors = other.predictors)
      return(stat.dt)
    }
  )
)
